#!/usr/bin/env python3
"""
Bitmap-font generator: Fitbit can't load font files, so we pre-render
each character as an 8-bit grayscale PNG (white glyph on black). At runtime
the build turns those into alpha masks, and the app tints them with the
colours in theme.js.

Outputs
  resources/glyphs/<set>/<charCode>.png     one image per character
  app/config/glyphs.js                      metrics the app lays out with

To change the typeface: drop a .ttf/.otf/.woff into tools/fonts/ and point
the SETS table below at it, then run:   npm run glyphs
Sizes are in screen px (1 design px = 1 Sense px), same as Figma font size.

Default fonts: Barlow Condensed (everything) and Barlow Semi Condensed
(battery), both SIL OFL 1.1 — see tools/fonts/*/OFL.txt.
Requires: pip install pillow
"""
import json
import math
import os
import shutil

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
FONTS = os.path.join(HERE, "fonts")


def condensed(weight):
    return os.path.join(FONTS, "barlow-condensed", "barlow-condensed-latin-%d-normal.woff" % weight)


def semi(weight):
    return os.path.join(FONTS, "barlow-semi-condensed", "barlow-semi-condensed-latin-%d-normal.woff" % weight)


DIGITS = "0123456789"
UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
LOWER = UPPER.lower()

# name → (font file, size px, characters)
SETS = {
    "time":     (condensed(500), 60, DIGITS + ":"),
    "timeAod":  (condensed(300), 104, DIGITS + ":"),
    "date":     (condensed(500), 30, UPPER + LOWER + DIGITS + " ,./-:"),
    "dateAod":  (condensed(400), 24, UPPER + LOWER + DIGITS + " ,./-:"),
    "label":    (condensed(500), 17, UPPER + " "),
    "value":    (condensed(500), 20, DIGITS + ",.- kmiHM"),
    "battery":  (semi(500), 17, DIGITS + "%-"),
}


def render_set(name, path, size, chars):
    f = ImageFont.truetype(path, size)
    ascent, descent = f.getmetrics()
    # Uniform image height per set: tallest ink above the baseline down to the
    # lowest ink below it, so every glyph shares one baseline.
    tops, bottoms = [], []
    for ch in chars:
        if ch == " ":
            continue
        l, t, r, b = f.getbbox(ch, anchor="ls")
        tops.append(t)
        bottoms.append(b)
    top, bottom = min(tops), max(bottoms)
    height = bottom - top

    out_dir = os.path.join(ROOT, "resources", "glyphs", name)
    shutil.rmtree(out_dir, ignore_errors=True)
    os.makedirs(out_dir)

    metrics = {}
    for ch in chars:
        adv = f.getlength(ch)
        if ch == " ":
            metrics[ch] = [round(adv, 1), 0, 0]
            continue
        l, t, r, b = f.getbbox(ch, anchor="ls")
        ox = min(0, l)               # ink left of the pen (rare)
        w = max(1, math.ceil(max(r, adv) - ox))
        img = Image.new("L", (w, height), 0)
        ImageDraw.Draw(img).text((-ox, -top), ch, font=f, fill=255, anchor="ls")
        img.save(os.path.join(out_dir, "%d.png" % ord(ch)), optimize=True)
        metrics[ch] = [round(adv, 1), w, ox]

    return {"dir": "glyphs/" + name, "h": height, "asc": -top, "g": metrics}


def main():
    data = {name: render_set(name, *spec) for name, spec in SETS.items()}
    js = [
        "/*",
        " * GENERATED by tools/generate_glyphs.py — do not edit by hand.",
        " * Bitmap font metrics. Per set: dir (resources path), h (image height),",
        " * asc (baseline offset from image top), g: char → [advance, width, offsetX].",
        " */",
        "",
    ]
    for name, d in data.items():
        js.append("export const %s = %s;" % (name, json.dumps(d, separators=(",", ":"))))
        js.append("")
    with open(os.path.join(ROOT, "app", "config", "glyphs.js"), "w") as fh:
        fh.write("\n".join(js))
    total = sum(len(d["g"]) for d in data.values())
    print("wrote %d glyphs in %d sets" % (total, len(data)))


if __name__ == "__main__":
    main()
